### ISSUE TITLE
Need Linux build with ubuntu 16.04 for pyqt5 support

### ISSUE THREAD

**Issue by suryacaprice** [cdrx/docker-pyinstaller#100]
Collecting PyQt5
  Downloading https://files.pythonhosted.org/packages/8c/90/82c62bbbadcca98e8c6fa84f1a638de1ed1c89e85368241e9cc43fcbc320/PyQt5-5.15.0.tar.gz (3.3MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /root/.pyenv/versions/3.7.5/bin/python3.7 /root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmps8wjraom
         cwd: /tmp/pip-install-wqxvip7n/PyQt5
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 103, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in prepare_metadata_for_build_wheel
        config_settings)
      File "/root/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 136, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-e_nvn7b0/overlay/lib/python3.7/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/tmp/pip-build-env-e_nvn7b0/overlay/lib/python3.7/site-packages/sipbuild/abstract_project.py", line 82, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-e_nvn7b0/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 477, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 62, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-e_nvn7b0/overlay/lib/python3.7/site-packages/pyqtbuild/project.py", line 86, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-e_nvn7b0/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 223, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-e_nvn7b0/overlay/lib/python3.7/site-packages/pyqtbuild/builder.py", line 68, in apply_user_defaults
        "specify a working qmake or add it to PATH")
    sipbuild.pyproject.PyProjectOptionException

Unable to install pyqt5 

i have created this https://hub.docker.com/repository/docker/suryacaprice/fbs-ubuntu16-py3.6/general 
But I get some error 
Digest: sha256:3a25c00d88e433b520388b4a8eb92e11086e60f908c70dfb7bc4aa064ae01b0c
Status: Downloaded newer image for suryacaprice/fbs-ubuntu16-py3.6:latest
: invalid option
Usage:	/bin/bash [GNU long option] [option] ...
	/bin/bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--rcfile
	--restricted
	--verbose
	--version
Shell options:
	-ilrsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
ERROR: Job failed: exit code 2

**Comment by Toilal** [comment]
https://github.com/cdrx/docker-pyinstaller/pull/90 This may help I think. But you have to clone my fork and build images locally.
